### PR TITLE
 this line was making the android cursor break.

### PR DESCRIPTION
**Pull request by minatonda**
Só removi a linha.
Estava quebrando em alguns dispositivos Android....
Agora não está mais.

### CODE REVIEW

**Comment by minatonda** [comment]
The second commit followed @pjaer

**Comment by luismiguelprs** [comment]
@neves, tem previsão para avaliação desse MR?
Estou com esse problema em alguns dispositivos android também. :cry:

**Comment by iamdubx** [comment]
This is aweful. 
You should type this on starter page - DOESN'T WORK ON MOBILE

**Comment by vjoao** [comment]
@iamdubx this is open source software. People doesn't owe you anything. If you want it to get better, fork it, change it and PR it. You don't need to offend other people`s work just because it doesn't fulfill your lazy needs.

If you don't like it, just find another mask plugin or, even better, build your own. If you are capable of doing the latter, please post the Github link.

**Comment by iamdubx** [comment]
@vjoao after investigating, I found out that Android bugs are common on ALL mask libraries! And all of them are using `type="tel"` to fix them! 

So I am sorry for my previous post. I think @neves maybe you can put some info about `type="tel"` into Docs? 

From this point, `vue-the-mask` is the most elegant solution for most usecases.

**Comment by minatonda** [comment]
Personally, for me it works with this pull request.
I tested Android O, Android N and KITKAT devices (S6,S5,MOTOG3,ZENFONE3).

I modified this code directly in .min.js in my project, and it is working.

I'm sorry for the problem of the colleague, I hope he finds a solution for this, and share with us, for when we have the same;)

**Comment by neves** [comment]
Fixed with version 0.11.0

**Pull request closed without merging**
